//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDAC_CMS.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ShippingSchedule : Controllers.ShippingSchedulesController
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShippingSchedule()
        {
            this.Bookings = new HashSet<Booking>();
        }

        public int ShippingScheduleID { get; set; }
        public string ShippingScheduleName { get; set; }
        public int VesselID { get; set; }
        public int DeparturePortID { get; set; }
        public int ArrivalPortID { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime ArrivalDateTime { get; set; }
        public string AdminID { get; set; }
        public string SpaceAvailable { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Port Port { get; set; }
        public virtual Port Port1 { get; set; }
        public virtual Vessel Vessel { get; set; }
    }
}
